version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.0
  aws-ecs: circleci/aws-ecs@1.3.0
jobs:
  update-aws-service:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - aws-ecs/update-service:
          family: '${APP_PREFIX}'
          cluster-name: '${APP_PREFIX}-cluster-euwest2'
          service-name: '${APP_PREFIX}-service'
          force-new-deployment: true
workflows:
  deploy:
    jobs:
      - update-aws-service:
          filters:
            branches:
              only:
                - master